name: opennz_ua
publish_to: 'none'
version: 0.1.4

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  either_dart: ^1.0.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: any
  rename_app: ^1.6.1
  gap: ^3.0.1
  url_launcher: ^6.3.0
  provider: ^6.1.2
  figma_squircle: ^0.5.3
  flutter_svg: 2.0.10
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
